In [ ]:
sklearn.feature_extraction.text.CountVectorizer

CountVectorizer class Convert a collection of text documents to a matrix of token counts

min_df : float in range [0.0, 1.0] or int, default=1
When building the vocabulary ignore terms that have a document frequency strictly lower than the given threshold. 
This value is also called cut-off in the literature.


In [59]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one about python.',
    'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)#Learn the vocabulary dictionary and return term-document matrix(matrix of term count)

feature_names= vectorizer.get_feature_names()
print(feature_names)

print(X.toarray())  
print(X) # sparse matrix is the one having zero entries ,occupy less space because space is not reserved for zero matrix entries

['about', 'and', 'document', 'first', 'is', 'one', 'python', 'second', 'the', 'third', 'this']
[[0 0 1 1 1 0 0 0 1 0 1]
 [0 0 2 0 1 0 0 1 1 0 1]
 [1 1 0 0 1 1 1 0 1 1 1]
 [0 0 1 1 1 0 0 0 1 0 1]]
  (0, 2)	1
  (0, 3)	1
  (0, 8)	1
  (0, 4)	1
  (0, 10)	1
  (1, 7)	1
  (1, 2)	2
  (1, 8)	1
  (1, 4)	1
  (1, 10)	1
  (2, 6)	1
  (2, 0)	1
  (2, 5)	1
  (2, 9)	1
  (2, 1)	1
  (2, 8)	1
  (2, 4)	1
  (2, 10)	1
  (3, 2)	1
  (3, 3)	1
  (3, 8)	1
  (3, 4)	1
  (3, 10)	1


In [60]:
import numpy as np
df = pd.DataFrame(data=np.array(X.toarray()),columns=feature_names)
print(df)

   about  and  document  first  is  one  python  second  the  third  this
0      0    0         1      1   1    0       0       0    1      0     1
1      0    0         2      0   1    0       0       1    1      0     1
2      1    1         0      0   1    1       1       0    1      1     1
3      0    0         1      1   1    0       0       0    1      0     1


In [37]:
from sklearn.feature_extraction.text import CountVectorizer

import numpy as np
import pandas as pd

 # training corpus
CORPUS = [   
'the sky is blue',
'sky is blue and sky is beautiful',
'the beautiful sky is so blue',
'i love blue cheese'
]

# the sky, sky is , is blue
# sky is , is blue, blue and, and sky is, is beautiful
# the beautiful,beautiful sky, sky is, is so, so blue
# i love, love blue, blue cheese

# test document
new_doc = ['loving this blue sky today']

 # 1 gram or individaul words only 
#try ngram_range(1,2)for 1 and 2 grams and (1,3), (2,2)  for 2 grams only -bag of bigrams, (3,3) for 3 grams only-bag of trigrams


def bow_extractor(corpus, ngram_range=(1,1)):
    
    vectorizer = CountVectorizer(min_df=1, ngram_range=ngram_range)
    #with min_df set to 1 to take terms having a minimum frequency of 1 in the overall document vector space.
    
    features = vectorizer.fit_transform(corpus) ##Learn the vocabulary dictionary and return term-document matrix.
    return vectorizer, features

# build bow vectorizer and get features

bow_vectorizer, bow_features = bow_extractor(CORPUS)
features = bow_features.todense() #Return a dense matrix representation of this matrix.

feature_names=bow_vectorizer.get_feature_names()
print (features)
print()
'''features2 = bow_features.toarray()
print (features2'''

# extract features from new document using built vectorizer
new_doc_features = bow_vectorizer.transform(new_doc)
new_doc_features = new_doc_features.todense()
new_doc_feature_names=bow_vectorizer.get_feature_names()
print (new_doc_features)
print()
print()
df = pd.DataFrame(data=np.array(features),columns=feature_names)
print(df)
print()
df = pd.DataFrame(data=np.array(new_doc_features),columns=new_doc_feature_names)
print(df)

[[0 0 1 0 1 0 1 0 1]
 [1 1 1 0 2 0 2 0 0]
 [0 1 1 0 1 0 1 1 1]
 [0 0 1 1 0 1 0 0 0]]

[[0 0 1 0 0 0 1 0 0]]


   and  beautiful  blue  cheese  is  love  sky  so  the
0    0          0     1       0   1     0    1   0    1
1    1          1     1       0   2     0    2   0    0
2    0          1     1       0   1     0    1   1    1
3    0          0     1       1   0     1    0   0    0

   and  beautiful  blue  cheese  is  love  sky  so  the
0    0          0     1       0   0     0    1   0    0


In [68]:
s= set( ['sky is' , 'is blue', 'blue and', 'and sky','sky is', 'is beautiful','the beautiful','beautiful sky', 'sky is', 'is so', 'so blue','i love', 'love blue', 'blue cheese'])
print(s)
print(len(s))

{'sky is', 'the beautiful', 'beautiful sky', 'and sky', 'is so', 'is beautiful', 'love blue', 'so blue', 'blue cheese', 'is blue', 'blue and', 'i love'}
12


In [33]:
from sklearn.feature_extraction.text import CountVectorizer

import numpy as np

 # training corpus
CORPUS = [   
'the sky is blue',
'sky is blue and sky is beautiful',
'the beautiful sky is so blue',
'i love blue cheese'
]
# test document
new_doc = ['loving this blue sky today']

 # 1 gram or individaul words only 
#try ngram_range(1,2)for 1 and 2 grams and (1,3), (2,2)  for 2 grams only -bag of bigrams, (3,3) for 3 grams only-bag of trigrams


def bow_extractor(corpus, ngram_range=(2,2)):
    
    vectorizer = CountVectorizer(min_df=1, ngram_range=ngram_range)
    #with min_df set to 1 to take terms having a minimum frequency of 1 in the overall document vector space.
    
    features = vectorizer.fit_transform(corpus) ##Learn the vocabulary dictionary and return term-document matrix.
    return vectorizer, features

# build bow vectorizer and get features

bow_vectorizer, bow_features = bow_extractor(CORPUS)
features = bow_features.todense() #Return a dense matrix representation of this matrix.

feature_names=bow_vectorizer.get_feature_names()
print (features)
df = pd.DataFrame(data=np.array(features),columns=feature_names)
print(df)

[[0 0 0 0 0 1 0 0 1 0 0 1]
 [1 0 1 0 1 1 0 0 2 0 0 0]
 [0 1 0 0 0 0 1 0 1 1 1 0]
 [0 0 0 1 0 0 0 1 0 0 0 0]]


NameError: name 'pd' is not defined

In [65]:
TF-IDF

NameError: name 'TF' is not defined

In [77]:
import pandas as pd
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
new_doc = ['loving this blue sky today']

def display_features(features, feature_names):
    
    df = pd.DataFrame(data=features, columns=feature_names)
    print (df)

In [43]:
CORPUS = [
'the sky is blue',
'sky is blue and sky is beautiful',
'the beautiful sky is so blue',
'i love blue cheese'
]
new_doc = ['loving this blue sky today']
def display_features(features, feature_names):
    
    df = pd.DataFrame(data=features, columns=feature_names)
    print (df)

def bow_extractor(corpus, ngram_range=(1,1)): # 1 gram or individaul words only
    # try ngram_range(1,2)for 1 and 2 grams and (1,3), (2,2)  for 2 grams only (3,3) for 3 grams only
    
    vectorizer = CountVectorizer(min_df=1, ngram_range=ngram_range)#with min_df set to 1 to take terms having a minimum frequency of 1 in the overall document vector space.
    features = vectorizer.fit_transform(corpus) ##Learn the vocabulary dictionary and return term-document matrix.
    return vectorizer, features
    
bow_vectorizer, bow_features = bow_extractor(CORPUS)
features = bow_features.todense()
print (features)
feature_names = bow_vectorizer.get_feature_names()
print()
print()
display_features(bow_features.todense(),feature_names)

new_doc_features = bow_vectorizer.transform(new_doc)
new_doc_features = new_doc_features.todense()
print (new_doc_features)
print()
print()

feature_names = bow_vectorizer.get_feature_names()
print (feature_names)

[[0 0 1 0 1 0 1 0 1]
 [1 1 1 0 2 0 2 0 0]
 [0 1 1 0 1 0 1 1 1]
 [0 0 1 1 0 1 0 0 0]]


   and  beautiful  blue  cheese  is  love  sky  so  the
0    0          0     1       0   1     0    1   0    1
1    1          1     1       0   2     0    2   0    0
2    0          1     1       0   1     0    1   1    1
3    0          0     1       1   0     1    0   0    0
[[0 0 1 0 0 0 1 0 0]]


['and', 'beautiful', 'blue', 'cheese', 'is', 'love', 'sky', 'so', 'the']


In [144]:
display_features(features, feature_names)
print()
display_features(new_doc_features, feature_names)

   and  beautiful  blue  cheese  is  love  sky  so  the
0    0          0     1       0   1     0    1   0    1
1    1          1     1       0   2     0    2   0    0
2    0          1     1       0   1     0    1   1    1
3    0          0     1       1   0     1    0   0    0

   and  beautiful  blue  cheese  is  love  sky  so  the
0    0          0     1       0   0     0    1   0    0


In [ ]:
TfidfTransformer(
    ["norm='l2'", 'use_idf=True', 'smooth_idf=True', 'sublinear_tf=False'],
)
Docstring:     
Transform a count matrix to a normalized tf or tf-idf representation

Tf means term-frequency while tf-idf means term-frequency times inverse
document-frequency. This is a common term weighting scheme in information
retrieval, that has also found good use in document classification.

The goal of using tf-idf instead of the raw frequencies of occurrence of a
token in a given document is to scale down(reduce the size of something) the impact of tokens that occur
very frequently in a given corpus and that are hence empirically less
informative than features that occur in a small fraction of the training
corpus.

The formula that is used to compute the tf-idf for a term t of a document d
in a document set is tf-idf(t, d) = tf(t, d) * idf(t), and the idf is
computed as idf(t) = log [ n / df(t) ] + 1 (if ``smooth_idf=False``), where
n is the total number of documents in the document set and df(t) is the
document frequency of t; the document frequency is the number of documents
in the document set that contain the term t. The effect of adding "1" to
the idf in the equation above is that terms with zero idf, i.e., terms
that occur in all documents in a training set, will not be entirely
ignored.
(Note that the idf formula above differs from the standard textbook
notation that defines the idf as
idf(t) = log [ n / (df(t) + 1) ]).

If ``smooth_idf=True`` (the default), the constant "1" is added to the
numerator and denominator of the idf as if an extra document was seen
containing every term in the collection exactly once, which prevents
zero divisions: idf(d, t) = log [ (1 + n) / (1 + df(d, t)) ] + 1.

Furthermore, the formulas used to compute tf and idf depend
on parameter settings that correspond to the SMART notation used in IR
as follows:

Tf is "n" (natural) by default, "l" (logarithmic) when
``sublinear_tf=True``.
Idf is "t" when use_idf is given, "n" (none) otherwise.
Normalization is "c" (cosine) when ``norm='l2'``, "n" (none)
when ``norm=None``

In [155]:
#getting the tfidf-based feature vectors, considering we have our Bag of Words feature vectors.
#the TfidfTransformer class, which helps us in computing the tfidfs for each document

'''In our implementation we will be adding 1 to the document frequency for each term just to indicate that we also have one more 
document in our corpus that essentially has every term in the vocabulary. 
This is to prevent potential division-by-zero errors and smoothen the inverse document frequencies. 
We also add 1 to the result of our idf computation to avoid ignoring terms completely that might have zero idf.

The final TF-IDF metric we will be using is a normalized version of the tfidf matrix we get from the product of tf and idf. 
We will normalize the tfidf matrix by dividing it with the L2 norm of the matrix, also known as the Euclidean norm, 
which is the square root of the sum of the square of each term’s tfidf weight. 
Mathematically we can represent the final tfidf feature vector as tfidf = tfidf /||tfidf||



smooth_idf : boolean (default=True)
    Smooth idf weights by adding one to document frequencies, as if an
    extra document was seen containing every term in the collection
    exactly once. Prevents zero divisions.
        
use_idf : boolean (default=True)
Enable inverse-document-frequency reweighting.


'''
from sklearn.feature_extraction.text import TfidfTransformer
def tfidf_transformer(bow_matrix):
    
    transformer = TfidfTransformer(norm='l2',
                                   smooth_idf=True,
                                   use_idf=True)
    tfidf_matrix = transformer.fit_transform(bow_matrix)
    return transformer, tfidf_matrix

# build tfidf transformer and show train corpus tfidf features
feature_names = bow_vectorizer.get_feature_names()

tfidf_trans, tdidf_features = tfidf_transformer(bow_features) # pass Bag of Words feature vectors.

features = np.round(tdidf_features.todense(), 2)

display_features(np.round(tdidf_features.todense(), 2), feature_names)



    and  beautiful  blue  cheese    is  love   sky    so   the
0  0.00       0.00  0.40    0.00  0.49  0.00  0.49  0.00  0.60
1  0.44       0.35  0.23    0.00  0.56  0.00  0.56  0.00  0.00
2  0.00       0.43  0.29    0.00  0.35  0.00  0.35  0.55  0.43
3  0.00       0.00  0.35    0.66  0.00  0.66  0.00  0.00  0.00


In [146]:
# compute TF-IDF matrix using TfidfTransformer
from sklearn.feature_extraction.text import TfidfTransformer
def tfidf_transformer(bow_matrix):
    
    transformer = TfidfTransformer(norm=None,
                                   smooth_idf=True,
                                   use_idf=True)
    tfidf_matrix = transformer.fit_transform(bow_matrix)
    return transformer, tfidf_matrix

# build tfidf transformer and show train corpus tfidf features
feature_names = bow_vectorizer.get_feature_names()

tfidf_trans, tdidf_features = tfidf_transformer(bow_features) # pass Bag of Words feature vectors.

features = np.round(tdidf_features.todense(), 2)

display_features(features, feature_names)

    and  beautiful  blue  cheese    is  love   sky    so   the
0  0.00       0.00   1.0    0.00  1.22  0.00  1.22  0.00  1.51
1  1.92       1.51   1.0    0.00  2.45  0.00  2.45  0.00  0.00
2  0.00       1.51   1.0    0.00  1.22  0.00  1.22  1.92  1.51
3  0.00       0.00   1.0    1.92  0.00  1.92  0.00  0.00  0.00


In [147]:
tmp_matrix=np.round(tdidf_features.toarray(),2)
print(tmp_matrix[0])


[0.   0.   1.   0.   1.22 0.   1.22 0.   1.51]


In [148]:
N=4
DF=3
tf=np.round(1+np.log((1+N)/(1+DF)),2)
print(tf)
tf=np.round(tf/np.sqrt(np.sum(np.square(tmp_matrix[0]))),2)
print(tf)

1.22
0.49


In [98]:
N=4
DF=2
tf=np.round(1+np.log((1+N)/(1+DF)),2)
print(tf)
tf=np.round(tf/np.sqrt(np.sum(np.square(tmp_matrix[0]))),2)
print(tf)

1.51
0.58


In [99]:
N=4
DF=1
tf=np.round(1+np.log((1+N)/(1+DF)),2)
print(tf)
tf=np.round(tf/np.sqrt(np.sum(np.square(tmp_matrix[0]))),2)
print(tf)

1.92
0.74


In [176]:
#show tfidf features for new_doc using built tfidf transformer
nd_tfidf = tfidf_trans.transform(new_doc_features)
nd_features = np.round(nd_tfidf.todense(), 2)
display_features(nd_features, feature_names)

   and  beautiful  blue  cheese   is  love   sky   so  the
0  0.0        0.0  0.63     0.0  0.0   0.0  0.77  0.0  0.0


In [99]:
#Compute TFiDF matrix your own, first find term freq,then  compute our document frequencies (DF) for each term based on the
#number of documents in which it occurs from bag of words feature matrix, now we have document frequencies, 
#we will compute the inverse document frequency (idf), finally compute the tfidf feature matrix using matrix multiplication
#
# show term frequencies from bag of words matrix

import scipy.sparse as sp
from numpy.linalg import norm
feature_names = bow_vectorizer.get_feature_names()

# compute term frequency
tf = bow_features.todense()
tf = np.array(tf, dtype='float64')

# show term frequencies
display_features(tf, feature_names)

   and  beautiful  blue  cheese   is  love  sky   so  the
0  0.0        0.0   1.0     0.0  1.0   0.0  1.0  0.0  1.0
1  1.0        1.0   1.0     0.0  2.0   0.0  2.0  0.0  0.0
2  0.0        1.0   1.0     0.0  1.0   0.0  1.0  1.0  1.0
3  0.0        0.0   1.0     1.0  0.0   1.0  0.0  0.0  0.0


In [100]:
# build the document frequency matrix

df = np.diff(sp.csc_matrix(bow_features, copy=True).indptr)
df = 1 + df # to smoothen idf later
# show document frequencies
display_features([df], feature_names)

   and  beautiful  blue  cheese  is  love  sky  so  the
0    2          3     5       2   4     2    4   2    3


In [157]:
# compute inverse document frequencies
total_docs = 1 + len(CORPUS)
idf = 1.0 + np.log(float(total_docs) / df)

# show inverse document frequencies
display_features([np.round(idf, 2)], feature_names)
print(idf.shape)

    and  beautiful  blue  cheese    is  love   sky    so   the
0  1.92       1.51   1.0    1.92  1.22  1.92  1.22  1.92  1.51
(9,)


In [156]:
# compute tfidf feature matrix
tfidf = tf * idf
# show tfidf feature matrix
display_features(np.round(tfidf, 2), feature_names)

    and  beautiful  blue  cheese    is  love   sky    so   the
0  0.00       0.00   1.0    0.00  1.22  0.00  1.22  0.00  1.51
1  1.92       1.51   1.0    0.00  2.45  0.00  2.45  0.00  0.00
2  0.00       1.51   1.0    0.00  1.22  0.00  1.22  1.92  1.51
3  0.00       0.00   1.0    1.92  0.00  1.92  0.00  0.00  0.00


In [ ]:
computes the tfidf norms for each document and then divides the tfidf weights
with the norm to give us the final desired tfidf matrix:

In [160]:
# compute L2 norms # square of sum of each squared term
norms = norm(tfidf, axis=1)
# print norms for each document
print(np.round(norms, 2))

[2.5  4.35 3.5  2.89]


In [161]:
# compute normalized tfidf
norm_tfidf = tfidf / norms[:, None]
# show final tfidf feature matrix
display_features(np.round(norm_tfidf, 2), feature_names)

    and  beautiful  blue  cheese    is  love   sky    so   the
0  0.00       0.00  0.40    0.00  0.49  0.00  0.49  0.00  0.60
1  0.44       0.35  0.23    0.00  0.56  0.00  0.56  0.00  0.00
2  0.00       0.43  0.29    0.00  0.35  0.00  0.35  0.55  0.43
3  0.00       0.00  0.35    0.66  0.00  0.66  0.00  0.00  0.00


In [175]:
print(norms)
print(norms[:])
print(norms.ndim)
print('ddaa',norms[:,None])
print('ddd',np.transpose(norms[:]))
print(norms[:,None].ndim)
print(norms[:,None].shape)
a=np.array([1,2,3,4,5])
print(a[:,None])


[2.50494598 4.35010407 3.49707286 2.88865719]
[2.50494598 4.35010407 3.49707286 2.88865719]
1
ddaa [[2.50494598]
 [4.35010407]
 [3.49707286]
 [2.88865719]]
ddd [2.50494598 4.35010407 3.49707286 2.88865719]
2
(4, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [46]:
#implement a genericfunction that can directly compute the tfidf-based feature vectors for documents from the
#raw documents themselves.function makes use of the TfidfVectorizer, which directly computes
#the tfidf vectors by taking the raw documents themselves as input and internally
#computing the term frequencies as well as the inverse document frequencies, eliminating
#the need to use the CountVectorizer for computing the term frequencies based on the
#Bag of Words model. Support is also present for adding n-grams to the feature vectors. 

from sklearn.feature_extraction.text import TfidfVectorizer
def tfidf_extractor(corpus, ngram_range=(1,1)):

    vectorizer = TfidfVectorizer(min_df=1,norm='l2',smooth_idf=True,use_idf=True,ngram_range=ngram_range)

    features = vectorizer.fit_transform(corpus)

    return vectorizer, features

In [47]:
# build tfidf vectorizer and get training corpus feature vectors
tfidf_vectorizer, tdidf_features = tfidf_extractor(CORPUS)
display_features(np.round(tdidf_features.todense(), 2), feature_names)

    and  beautiful  blue  cheese    is  love   sky    so   the
0  0.00       0.00  0.40    0.00  0.49  0.00  0.49  0.00  0.60
1  0.44       0.35  0.23    0.00  0.56  0.00  0.56  0.00  0.00
2  0.00       0.43  0.29    0.00  0.35  0.00  0.35  0.55  0.43
3  0.00       0.00  0.35    0.66  0.00  0.66  0.00  0.00  0.00


In [180]:
# get tfidf feature vector for the new document
nd_tfidf = tfidf_vectorizer.transform(new_doc)
display_features(np.round(nd_tfidf.todense(), 2), feature_names)

   and  beautiful  blue  cheese   is  love   sky   so  the
0  0.0        0.0  0.63     0.0  0.0   0.0  0.77  0.0  0.0


In [113]:
column i are stored in indices[indptr[i]:indptr[i+1]]
coloumn 0               indices[indptr[0]:indptr[1]]  # indices[0,2]
column 1                indices[indptr[1]:indptr[2]]  # indices[2,3]
column 2                 indices[indptr[2]:indptr[3]] #indices[3,6]


row = np.array([0, 2, 2, 0, 1, 2])
col = np.array([0, 0, 1, 2, 2, 2])
data = np.array([1, 2, 3, 4, 5, 6])
print(sp.csc_matrix((data, (row, col)), shape=(3, 3)).toarray())
print(sp.csc_matrix((data, (row, col)), shape=(3, 3).indptr))

[[1 0 4]
 [0 0 5]
 [2 3 6]]


AttributeError: 'tuple' object has no attribute 'indptr'

In [ ]:
There are various approaches to creating more advanced word vectorization models for
extracting features from text data. Here we will discuss a couple of them that use Google’s
popular word2vec algorithm. The word2vec model, released in 2013 by Google, is a neural
network–based implementation that learns distributed vector representations of words
based on continuous Bag of Words and skip-gram–based architectures. 
The word2vec framework is much faster than other neural network–based implementations and does
not require manual labels to create meaningful representations among words. You can
find more details on Google’s word2vec project at https://code.google.com/archive/p/
word2vec/. You can even try out some of the implementations yourself if you are interested.
We will be using the gensim library in our implementation, which is Python
implementation for word2vec that provides several high-level interfaces for easily building
these models. The basic idea is to provide a corpus of documents as input and get feature
vectors for them as output. Internally, it constructs a vocabulary based on the input text
documents and learns vector representations for words based on various techniques
mentioned earlier, and once this is complete, it builds a model that can be used to
extract word vectors for each word in a document. Using various techniques like average
weighting or tfidf weighting, we can compute the averaged vector representation of a
document using its word vectors. You can get more details about the interface for gensim‘s

In [ ]:
conda install gensim
The word2vec tool takes a text corpus as input and produces the word vectors as output.
It first constructs a vocabulary from the training text data and then learns vector representation of words. 
The resulting word vector file can be used as features in many natural language processing and machine learning applications.

A simple way to investigate the learned representations is to find the closest words for a user-specified word. 
The distance tool serves that purpose. For example, if you enter 'france', distance will display the most similar words and their distances to 'france', which should look like:
 https://www.kdnuggets.com/2018/04/robust-word2vec-models-gensim.html
    https://skymind.ai/wiki/word2vec

In [97]:
import gensim
import nltk
 # training corpus
CORPUS = [   
'the sky is blue',
'sky is blue and sky is beautiful',
'the beautiful sky is so blue',
'i love blue cheese'
]
# test document
new_doc = ['loving this blue sky today']

TOKENIZED_CORPUS = [nltk.word_tokenize(sentence) 
                    for sentence in CORPUS]
tokenized_new_doc = [nltk.word_tokenize(sentence) 
                    for sentence in new_doc]                        

model = gensim.models.Word2Vec(TOKENIZED_CORPUS, 
                               size=10,
                               window=10,
                               min_count=2,
                               sample=1e-3)


print(model.wv.index2word)
#print(model['the'].)
#for i in TOKENIZED_CORPUS:
    #print(i)

['sky', 'is', 'blue', 'the', 'beautiful']


In [20]:
 #In gensim 1.0.0+, the `index2word` list of words has moved to the model's `wv` property (a KeyedVectors instance).
  #  So replace `model.index2word` with `model.wv.index2word`.
#https://stackoverflow.com/questions/31440803/how-to-fetch-vectors-for-a-word-list-with-word2vec


my_dict = dict({})
#for idx, key in enumerate(model.wv.vocab):
 #   my_dict[key] = model.wv[key]
    # Or my_dict[key] = model.wv.get_vector(key)
    # Or my_dict[key] = model.wv.word_vec(key, use_norm=False)
    
import numpy as np
def average_word_vectors(words, model, vocabulary, num_features):
    
    feature_vector = np.zeros((num_features,),dtype="float64")
    nwords = 0.
    
    for word in words:
        print()
        print('word is ', word)
        if word in vocabulary: 
            nwords = nwords + 1
            #print('word {} and feature vector {} '.format(word,feature_vector))
            feature_vector = np.add(feature_vector, model[word])
            print()
            print('After word {} and feature vector {} '.format(word,model[word]))
            print()
            print('After addition word {} and feature vector {} '.format(word,feature_vector))
            
            my_dict[word]=model[word]
    
    print('hello')
    print('')
    print('')
    #for key,value in my_dict.items():
     #   print(key,np.round(value,3))
    if nwords:
        feature_vector = np.divide(feature_vector, nwords)
        print('finalized feature vector', feature_vector)
        
    return feature_vector
    
   
 def averaged_word_vectorizer(corpus, model, num_features):
    vocabulary = set(model.wv.index2word)
    #print('index2word ',model.wv.index2word)
    #print('vocab is ',vocabulary)
    
    features = [average_word_vectors(tokenized_sentence, model, vocabulary, num_features)
                    for tokenized_sentence in corpus]
    
    return np.array(features)

# get averaged word vectors for our training CORPUS

avg_word_vec_features = averaged_word_vectorizer(corpus=TOKENIZED_CORPUS, model=model,num_features=10)

print (np.round(avg_word_vec_features, 3))
#for key,value in my_dict.items():
 #   print(key,np.round(value,3))


word is  the

After word the and feature vector [ 0.04696456  0.04587301 -0.03998681 -0.04094198 -0.04281063 -0.03340809
  0.01781495  0.02247143  0.03157189  0.03632472] 

After addition word the and feature vector [ 0.04696456  0.04587301 -0.03998681 -0.04094198 -0.04281063 -0.03340809
  0.01781495  0.02247143  0.03157189  0.03632472] 

word is  sky

After word sky and feature vector [ 0.04317668 -0.0389986   0.01506065 -0.03560273 -0.00640112 -0.00782156
  0.00584124 -0.00672364 -0.02584449 -0.02584974] 

After addition word sky and feature vector [ 0.09014125  0.00687441 -0.02492616 -0.07654471 -0.04921175 -0.04122965
  0.02365619  0.01574779  0.0057274   0.01047499] 

word is  is

After word is and feature vector [-0.02266192 -0.00251063 -0.03345118 -0.04034328  0.00706533 -0.02801719
  0.03403306 -0.04139802  0.01580966  0.00674342] 

After addition word is and feature vector [ 0.06747933  0.00436378 -0.05837735 -0.11688799 -0.04214642 -0.06924684
  0.05768925 -0.02565023  0.021

C:\Users\Atif Khan\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\Atif Khan\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
C:\Users\Atif Khan\Anaconda3\lib\site-packages\ipykernel_launcher.py:30: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).


In [31]:
##The purpose and usefulness of Word2vec is to group the vectors of similar words together in vectorspace. 
#That is, it detects similarities mathematically. Word2vec creates vectors 
#that are distributed numerical representations of word features, features such as the context of individual words.

the= np.array([ 0.04696456,  0.04587301, -0.03998681, -0.04094198, -0.04281063, -0.03340809, 0.01781495,  0.02247143,  0.03157189,  0.03632472]) 
sky= np.array([ 0.04317668, -0.0389986,   0.01506065, -0.03560273, -0.00640112, -0.00782156, 0.00584124, -0.00672364, -0.02584449, -0.02584974] )

isw= np.array([-0.02266192, -0.00251063, -0.03345118, -0.04034328,  0.00706533, -0.02801719, 0.03403306, -0.04139802,  0.01580966,  0.00674342] )

blue= np.array([-0.0284033,   0.01511517,  0.01588725, -0.04928996,  0.03953237, -0.01278873, -0.02903343,  0.02796526,  0.04616746, -0.03628164]) 

total=np.sum((the,sky,isw,blue),axis=0)
print(total)
print()
print(total/4)

##[ 0.03907602  0.01947895 -0.04249009 -0.16617795 -0.00261405 -0.08203557
 # 0.02865582  0.00231503  0.06770452 -0.01906324]

[ 0.03907602  0.01947895 -0.04249009 -0.16617795 -0.00261405 -0.08203557
  0.02865582  0.00231503  0.06770452 -0.01906324]

[ 0.00976901  0.00486974 -0.01062252 -0.04154449 -0.00065351 -0.02050889
  0.00716395  0.00057876  0.01692613 -0.00476581]


In [38]:
import numpy as np
data=np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
indptr= np.array([ 0, 2, 2, 6, 8, 10])  # row major order indptr refers to rows and indices refers to columnsand viceversa
indices= np.array([3, 4, 0, 1, 3, 4, 1, 3, 0, 4])
doubled_data = [n * 2 for n in data]
mat_csr = sp.csr_matrix((doubled_data, indptr, indices), shape=(5, 5))
display_matrix(mat_csr.todense())

NameError: name 'sp' is not defined

In [122]:
print(bow_features)
#print(bow_features.toarray())
print('--------------------------')
print(sp.csc_matrix(bow_features, copy=True).toarray())

  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 6)	1
  (0, 8)	1
  (1, 1)	2
  (1, 3)	1
  (1, 5)	1
  (1, 6)	1
  (1, 8)	1
  (2, 0)	1
  (2, 3)	1
  (2, 4)	1
  (2, 6)	1
  (2, 7)	1
  (2, 8)	1
  (3, 1)	1
  (3, 2)	1
  (3, 3)	1
  (3, 6)	1
  (3, 8)	1
--------------------------
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [ ]:
We will now compute our document frequencies (DF) for each term based on the number of documents in which it occurs. 
The following snippet shows how to obtain it from our Bag of Words feature matrix:

In [128]:
The compressed sparse row (CSR) or compressed row storage (CRS) or Yale format represents a matrix M by three (one-dimensional)
arrays, that respectively contain nonzero values, the extents of rows, and column indices. 
It is similar to COO, but compresses the row indices, hence the name. 
This format allows fast row access and matrix-vector multiplications (Mx). 
The CSR format has been in use since at least the mid-1960s, with the first complete description appearing in 1967.[4]

The CSR format stores a sparse m × n matrix M in row form using three (one-dimensional) arrays (A, IA, JA).
Let NNZ denote the number of nonzero entries in M. (Note that zero-based indices shall be used here.)
Illustration of row-major order compared to column-major order
https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_.28CSR.2C_CRS_or_Yale_format.29
    http://heydenberk.com/blog/posts/sparse-matrix-representations-in-scipy/
The array A is of length NNZ and holds all the nonzero entries of M in left-to-right top-to-bottom ("row-major") order.
The array IA is of length m + 1. It is defined by this recursive definition:
IA[0] = 0
IA[i] = IA[i − 1] + (number of nonzero elements on the (i-1)-th row in the original matrix)
Thus, the first m elements of IA store the index into A of the first nonzero element in each row of M, and the last element IA[m+1] stores NNZ, the number of elements in A, which can be also thought of as the index in A of first element of a phantom row just beyond the end of the matrix M. The values of the i-th row of the original matrix is read from the elements A[IA[i]] to A[IA[i + 1] − 1] (inclusive on both ends), i.e. from the start of one row to the last index just before the start of the next.[5]
The third array, JA, contains the column index in M of each element of A and hence is of length NNZ as well.

SyntaxError: invalid syntax (<ipython-input-128-ce129c445b2f>, line 1)

In [136]:
#The NumPy diff function “np.diff()” calculates the difference between subsequent values in a NumPy array.

import numpy as np
# Fibonacci Sequence with first 8 numbers
fibs = np.array([0, 1, 1, 2, 3, 5, 8, 13, 21])
diff_fibs = np.diff(fibs)
print(diff_fibs)
# [1 0 1 1 2 3 5 8]

[1 0 1 1 2 3 5 8]


In [139]:
# build the document frequency matrix
print(sp.csc_matrix(bow_features, copy=True).indptr)  # poiner (0,1) shows start and end index of 1st column,1 is not included
# and in the index array, 0 refers to 1 element in the index array, which is 2 lie in 3rd row of 1st column
# poiner (1,4) shows start and end index of 2nd colum column,4 is not included, and covers 3 elements of 2nd col in the index array
# and in the index array, 0 refers to 1 element in the index array, which is 2 lie in 3rd row of 1st column

#IA[i] = IA[i − 1] + (number of nonzero elements on the (i-1)-th colum in the original matrix) => IA[1]=A[0]+ no of elements in columns 0=0+1=1
#=> IA[2]= IA[1]+ no of elements in 1 columns=1+3= 4

'''The values of the i-th column of the original matrix is read from the elements A[IA[i]] to A[IA[i + 1] − 1] (inclusive on 
both ends), i.e. from the start of one row to the last index just before the start of the next'''
"the values of 0 the column   A[IA[0] to A[IA[1]-1]  => A[0] to A[0]  => 1 to 1"
"the values of 1st column   A[IA[1] to A[IA[2]-1]  => A[1] to A[3]  => 1 to 3" 


print('\nindices stores row index of each element of data array', sp.csc_matrix(bow_features, copy=True).indices)
print('\ndata is', sp.csc_matrix(bow_features, copy=True).data)
print('\n', sp.csc_matrix(bow_features, copy=True).toarray())
df = np.diff(sp.csc_matrix(bow_features, copy=True).indptr)
print('document freq ',df)
display_features([df], feature_names)
df = 1 + df # to smoothen idf later
'''Remember that we have added 1 to each frequency value to
smoothen the idf values later and prevent division-by-zero errors by assuming we have a
document (imaginary) that has all the terms once.'''
# show document frequencies
print()
print()
display_features([df], feature_names)

print(bow_features.shape)

[ 0  1  4  6 10 11 12 16 17 21]

indices stores row index of each element of data array [2 0 1 3 0 3 0 1 2 3 2 1 0 1 2 3 2 0 1 2 3]

data is [1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

 [[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
document freq  [1 3 2 4 1 1 4 1 4]
   and  document  first  is  one  second  the  third  this
0    1         3      2   4    1       1    4      1     4


   and  document  first  is  one  second  the  third  this
0    2         4      3   5    2       2    5      2     5
(4, 9)


In [ ]:
These days, I’m working on some text classification works, and I use gensim=’s =doc2vec function.

When using gensim, it shows this warning message: ``` C extension not loaded for Word2Vec, training will be slow. ```

I search this on Internet and found that gensim has rewrite some part of the code using `cython` rather than `numpy` to get better performance. A compiler is required to enable this feature.

I tried to install mingw and add it into the path, but it’s not working.

Finally, I tried to install Visual C++ Build Tools and it works.
https://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtools_full.exe

If this output a none -1 digit, then it’s fine. ```python3 from gensim.models import word2vec print(word2vec.FAST_VERSION) ```

In [88]:
from sklearn.feature_extraction.text import TfidfVectorizer
def tfidf_extractor(corpus, ngram_range=(1,1)):

    vectorizer = TfidfVectorizer(min_df=1,norm='l2',smooth_idf=True,use_idf=True,ngram_range=ngram_range)

    features = vectorizer.fit_transform(corpus)

    return vectorizer, features

# build tfidf vectorizer and get training corpus feature vectors
tfidf_vectorizer, tdidf_features = tfidf_extractor(CORPUS)
display_features(np.round(tdidf_features.todense(), 2), feature_names)



print()
print(np.round(tdidf_features.todense(),2))

print()
print(tfidf_vectorizer.vocabulary_)
print()
print(TOKENIZED_CORPUS)
print()
print(tdidf_features)
docs_tfidfs = [(doc, doc_tfidf) for doc, doc_tfidf 
                   in zip(TOKENIZED_CORPUS, list(np.round(tdidf_features.todense(),2)))]
print(docs_tfidfs)

a=np.zeros((10,))
print(a.shape)



    and  beautiful  blue  cheese    is  love   sky    so   the
0  0.00       0.00  0.40    0.00  0.49  0.00  0.49  0.00  0.60
1  0.44       0.35  0.23    0.00  0.56  0.00  0.56  0.00  0.00
2  0.00       0.43  0.29    0.00  0.35  0.00  0.35  0.55  0.43
3  0.00       0.00  0.35    0.66  0.00  0.66  0.00  0.00  0.00

[[0.   0.   0.4  0.   0.49 0.   0.49 0.   0.6 ]
 [0.44 0.35 0.23 0.   0.56 0.   0.56 0.   0.  ]
 [0.   0.43 0.29 0.   0.35 0.   0.35 0.55 0.43]
 [0.   0.   0.35 0.66 0.   0.66 0.   0.   0.  ]]

{'the': 8, 'sky': 6, 'is': 4, 'blue': 2, 'and': 0, 'beautiful': 1, 'so': 7, 'love': 5, 'cheese': 3}

[['the', 'sky', 'is', 'blue'], ['sky', 'is', 'blue', 'and', 'sky', 'is', 'beautiful'], ['the', 'beautiful', 'sky', 'is', 'so', 'blue'], ['i', 'love', 'blue', 'cheese']]

  (0, 8)	0.6031370082211672
  (0, 6)	0.4882913888670788
  (0, 4)	0.4882913888670788
  (0, 2)	0.3992102058196136
  (1, 6)	0.5623513975308212
  (1, 4)	0.5623513975308212
  (1, 2)	0.22987955785181605
  (1, 0)	0.44051606615

In [96]:
def tfidf_wtd_avg_word_vectors(words, tfidf_vector, tfidf_vocabulary, model, num_features):
    
    #print(tfidf_vector[0, tfidf_vocabulary.get(word)])
    print()
    word_tfidfs = [tfidf_vector[0, tfidf_vocabulary.get(word)] #tfidf_vector[0,8] refers to entry in the matrix for the
                   if tfidf_vocabulary.get(word) 
                   else 0 for word in words]
   # print('hello')
    #print(word_tfidfs)
    #print()
    word_tfidf_map = {word:tfidf_val for word, tfidf_val in zip(words, word_tfidfs)} # mapping of words to TFIDS
    
    feature_vector = np.zeros((num_features,),dtype="float64") # one dimensioanl array of 10 zeros
    vocabulary = set(model.wv.index2word)
    #print(vocabulary)
    #print('hhhhhhh ',model.wv.index2word)
    wts = 0
    for word in words:
        if word in vocabulary: 
            word_vector = model[word]
            weighted_word_vector = word_tfidf_map[word] * word_vector # multiply word vector with its TFiDf value
            wts = wts + word_tfidf_map[word]            # sum up the word TFIDf
            feature_vector = np.add(feature_vector, weighted_word_vector)
    if wts:
        feature_vector = np.divide(feature_vector, wts)
        
    return feature_vector



def tfidf_weighted_averaged_word_vectorizer(corpus, tfidf_vectors, 
                                   tfidf_vocabulary, model, num_features):
                                       
    docs_tfidfs = [(doc, doc_tfidf) 
                   for doc, doc_tfidf 
                   in zip(corpus, tfidf_vectors)]# combine 1st document with thier TF-IDS and so on
    
    features = [tfidf_wtd_avg_word_vectors (tokenized_sentence, tfidf, tfidf_vocabulary, model, num_features)
                    for tokenized_sentence, tfidf in docs_tfidfs]
   # print('here are finalized feature set for four documents ',features)
    
    return np.array(features) 



corpus_tfidf = tdidf_features
vocab = tfidf_vectorizer.vocabulary_  # dictionary of unique words along with column index

#{'the': 8, 'sky': 6, 'is': 4, 'blue': 2, 'and': 0, 'beautiful': 1, 'so': 7, 'love': 5, 'cheese': 3}

wt_tfidf_word_vec_features = tfidf_weighted_averaged_word_vectorizer(corpus=TOKENIZED_CORPUS,
                                                                     tfidf_vectors=corpus_tfidf,
                                                                     tfidf_vocabulary=vocab,
                                                                     model=model, 
                                                                     num_features=10)
print(np.round(wt_tfidf_word_vec_features, 3))
print()

nd_wt_tfidf_word_vec_features = tfidf_weighted_averaged_word_vectorizer(corpus=tokenized_new_doc,
                                                                     tfidf_vectors=corpus_tfidf,
                                                                     tfidf_vocabulary=vocab,
                                                                     model=model, 
                                                                     num_features=10)
print(np.round(nd_wt_tfidf_word_vec_features, 3))  
                                                     





[[ 0.014  0.007 -0.014 -0.041 -0.005 -0.022  0.009  0.001  0.016 -0.001]
 [ 0.003 -0.017 -0.004 -0.036  0.005 -0.014  0.014 -0.021  0.004 -0.007]
 [ 0.006  0.002 -0.007 -0.036 -0.002 -0.013  0.008 -0.008  0.021  0.005]
 [-0.028  0.015  0.016 -0.049  0.04  -0.013 -0.029  0.028  0.046 -0.036]]


[[ 0.011 -0.015  0.015 -0.042  0.014 -0.01  -0.01   0.009  0.007 -0.031]]


C:\Users\Atif Khan\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).


In [95]:
from gensim.models import word2vec 
print(word2vec.FAST_VERSION)

1
